version: "3.9"

x-ollama-env: &ollama-env
  OLLAMA_HOST: "http://host.docker.internal:11434"

services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      <<: *ollama-env
      SESSION_SECRET_KEY: "change-me"
      SYNC_DATABASE_URL: "sqlite:///./data/app.db"
      ASYNC_DATABASE_URL: "sqlite+aiosqlite:///./data/app.db"
      EMBED_PATH: ${EMBED_PATH:-Qwen3-Embedding-8B.Q4_0.gguf}
      RERANK_PATH: ${RERANK_PATH:-Qwen3-Reranker-0.6B-Q8_0.safetensors}
      ENABLE_RERANK: ${ENABLE_RERANK:-false}
    volumes:
      - pipcache:/root/.cache/pip
      - ./apps/backend:/usr/src/app
      - sqlite-data:/usr/src/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      retries: 5
    mem_limit: 8g
    restart: unless-stopped

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
    volumes:
      - ./apps/frontend:/usr/src/app
      - node-modules:/usr/src/app/node_modules
    depends_on:
      backend:
        condition: service_healthy
    mem_limit: 1g
    restart: unless-stopped

volumes:
  sqlite-data:
  node-modules:
  pipcache:
    driver_opts:
      o: O
